Milestone #2: Implementing Works and About Me sections of the Mobile version
joseph07-drack/portfolio pull request #2
Opened 2022-03-15 20:54 UTC by joseph07-drack

During this milestone, I implement the Works and About Me section.
Different things are possible from now like:
- getting the list of the projects
-  getting some details about my experience as a web developer
-  Getting some language stack that I can use to build different applications

Different tools make this implementation possible and working. Below is the list I used to accomplish this milestone:
1. HTML
2. CSS
3. Linters
4. NPM

2022-03-15 21:29 UTC, AnselemOdims requested changes
### Hi @joseph07-drack , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-15 21:29 UTC, AnselemOdims commented on index.html
> +          <a href="#" class="medias">let's connect</a>
- [ ] Good job on this but this is supposed to be a header tag `hx`. Kindly change it to be a header tag

2022-03-15 21:29 UTC, AnselemOdims commented on index.html
> +            <h3>languages</h3>
- [ ] Please kindly ensure the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`

```
<ul>
<li>Languages</li>
<li>Frameworks</li>
<li>Skills</li>
</ul>
```

2022-03-15 21:29 UTC, AnselemOdims commented on index.html
> +            <button type="button" class="btn btn-enabled">See project</button>
- [ ] Kindly make sure the margin between the cards and the sides of the page matches the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/158474481-37c2d737-95f9-4f78-8081-eb7362f9e592.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/158474400-953ad09c-0c54-42b0-83e2-a3d5ee58dd9e.png)

2022-03-15 21:29 UTC, AnselemOdims commented on index.html
> +              hestiate to contact me.
- [ ] Please ensure that the padding at the top of this section has enough room. At the moment, it does not exactly match the original design.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/158474990-22125383-e70a-4f2d-8165-3e9d4fde1ca0.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/158474929-0c21f23b-5f6e-4021-99ca-01b88f3097d1.png)

2022-03-15 21:29 UTC, AnselemOdims commented on index.html
> +            </li>
- [ ] Please ensure that this section matched the original design guidelines (margins, paddings, spacing etc). At the moment, the original design is centered while yours is not
- [ ] Also try and prevent the horizontal scrolling as this does not create a good user experience.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/158475458-837a0818-6b36-464b-a5ee-f3b6f16d7e95.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/158475539-74fa5bdc-19f5-4879-8c45-23bf7fc8a6c2.png)

2022-03-17 18:33 UTC, karvel-code approved these changes
Hi @joseph07-drack ,

## Status: APPROVED!!! 🥇 💯  
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 13:49 UTC, merged