Milestone #3: Implement contact form and finish the mobile version
joseph07-drack/portfolio pull request #3
Opened 2022-03-22 20:55 UTC by joseph07-drack

For this milestone, I learned how  :
- Create forms with HTML5 validations. ✔️
-  Use the formspree to test the form ✔️
-  Understand the importance of UX. ✔️
-  Apply coding best practices ✔️
- Understand how to parse a Figma design to create a UI. ✔️

2022-03-22 21:34 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @joseph07-drack, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good PR title and description
✔️ Good commit messages

## Required 
- [ ] Kindly add collaborator information to the readme file.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 21:34 UTC, sja-thedude commented on index.html
> +                size="30"
- [ ] Kindly change the `size` for input text to `max length` as per requirements.

2022-03-22 21:34 UTC, sja-thedude commented on style.css
> +  background-image: url('./images/contact-form-shape.png');
- [ ] Kindly fix the background image for the entire section of the contact form as per the Figma design.
- Your design:
<img width="367" alt="Screenshot 2022-03-23 at 12 19 47 AM" src="https://user-images.githubusercontent.com/70269507/159579325-ff17bc73-1740-4a85-a43b-b2348728cc16.png">

- Figma design:
<img width="367" alt="Screenshot 2022-03-23 at 12 20 32 AM" src="https://user-images.githubusercontent.com/70269507/159579357-7a97284a-3b4f-4a7f-8eff-0c546fb5fdbe.png">

2022-03-23 10:54 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi team, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 11:36 UTC, joseph07-drack commented
Thank you so much @[Amrhub](https://github.com/Amrhub)

2022-03-23 11:37 UTC, joseph07-drack commented
Thank you very much @Amrhub

2022-03-23 11:37 UTC, merged